# Generated by Django 3.1.2 on 2020-11-06 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20201029_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='header_image',
            field=models.ImageField(default='D:\\KeithelSeva.in\\design\\sample.png', upload_to='images/'),
        ),
    ]
