# Generated by Django 3.1.2 on 2020-11-06 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20201106_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='header_image',
            field=models.ImageField(default='D:\\KeithelSeva.in\\design\\sample.png', upload_to='images/'),
        ),
    ]
