# Generated by Django 3.1.2 on 2020-11-07 17:07

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_exchangemethod_paymentmethod_servicearea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=multiselectfield.db.fields.MultiSelectField(max_length=200),
        ),
    ]
