# Generated by Django 3.1.2 on 2020-11-07 17:24

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20201107_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='exchangemethod',
            name='exchange_method',
            field=multiselectfield.db.fields.MultiSelectField(max_length=200),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='payment_method',
            field=multiselectfield.db.fields.MultiSelectField(max_length=200),
        ),
        migrations.AlterField(
            model_name='servicearea',
            name='service_area',
            field=multiselectfield.db.fields.MultiSelectField(max_length=200),
        ),
    ]
