# Generated by Django 3.1.2 on 2020-11-07 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_auto_20201107_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangemethod',
            name='exchange_method',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='payment_method',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='servicearea',
            name='service_area',
            field=models.CharField(max_length=255),
        ),
    ]
