# Generated by Django 3.1.2 on 2020-11-07 18:17

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_auto_20201107_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='exchange_method',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='payment_method',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='service_area',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, max_length=200, null=True),
        ),
    ]
