# Generated by Django 3.1.2 on 2020-11-07 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_auto_20201107_2352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='service_area',
        ),
        migrations.AddField(
            model_name='profile',
            name='service_area',
            field=models.ManyToManyField(blank=True, null=True, to='website.ServiceArea'),
        ),
    ]
