# Generated by Django 3.1.2 on 2020-11-08 07:22

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_auto_20201108_0102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='service_area',
        ),
        migrations.AddField(
            model_name='profile',
            name='service_area',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('kakching', 'kakching'), ('imphal', 'imphal')], max_length=15, null=True),
        ),
    ]
