# Generated by Django 3.1.2 on 2020-11-12 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_auto_20201109_0839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='exchange_method',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='service_area',
        ),
    ]
