# Generated by Django 3.1.2 on 2020-11-15 08:23

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='exchange_method',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('pick up', 'pick up'), ('delivery', 'delivery')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='payment_method',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('cash', 'cash'), ('upi', 'upi')], max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='service_area',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('kakching', 'kakching'), ('imphal', 'imphal')], max_length=15, null=True),
        ),
    ]
